config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :chapters
  resources :users, only: [:index, :create, :show, :edit, :destroy, :update] do
    resources :books, only: [:new, :show, :index, :edit]
  end
  resources :genres, only: [:index, :create, :show] do
    resources :books, only: [:index]
  end
  resources :books, only: [:index, :show, :create, :update, :destroy] do
    resources :comments, only: [:create]
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_FB'
  root 'application#index'
  post '/follow/:id' => 'books#follow', as: :follow
  get 'comments/:id/comment_data', to: 'comments#comment_data'
  delete '/comments' => 'comments#destroy', as: :destroy
  post '/unfollow/:id' => 'books#unfollow', as: :unfollow
  get '/hikari_faves' => 'books#hikari_faves'
  get '/users/:id/blog' => 'users#blog', as: :blog
  get '/users/:id/blog/edit' => 'users#editblog', as: :edit_blog

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_books
  has_many :books, through: :user_books
  has_many :comments

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'FollowingFollower'
  has_many :following, through: :following_relationships, source: :following

  has_secure_password

  validates :username, presence: true, uniqueness: true, on: :create
  before_create validates :email, presence: true, uniqueness: true, on: :create
  before_create validates :password, presence: true, confirmation: true, on: :create
  before_create validates :password_confirmation, presence: true, on: :create

  # validates_presence_of :password, :on => :create, :if => :password_required
  # def validate_updated_user
  #   self.username.present?
  #   self.password.present?
  #   self.password_confirmation.present? &&  self.password_confirmation == self.password
  # end

  def user_book_ids
    self.books.uniq.collect do |book|
      book.id
    end
  end

  # def author_list
  #   self.map do |user_id|  User.find_by(id: user_id).username
  #   end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_user
skip_before_action :set_user, only: [:destroy, :create, :index, :new]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @book_ids = @user.user_book_ids
    # render json: @user
  end

  def edit
    if @user.nil?
      redirect_to users_path, alert: "Author not found."
    elsif !@user.uid.nil?
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find_by(username: params[:username])
    @user.destroy
    redirect_to '/'
  end

  def blog
  end

  def editblog
    redirect_to blog_path if @user != current_user
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:id, :email, :username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%if @user.errors.any?%>
<div id="error_explanation">
<h2><%=pluralize(@user.errors.count, "error")%> popped up:</h2>
  <%@user.errors.full_messages.each do |e|%>
  <li><%=e%></li>
</div>
  <%end%>
<%end%>
<div class="signup">
    <%=f.label :username%>
    <%=f.text_field :username, placeholder: "Username"%>
    <br></br>
    <%=f.label :email%>
    <%=f.text_field :email, placeholder: "Email"%>
  <div class="signup-password"
    <br></br>
    <%=f.label :password%>
    <%=f.text_field :password, placeholder: "Password"%>
    <br></br>
  <div>
</div>

app/views/users/_story_list.html.erb
Stories You're Following:
  <%user.following.each do |book|%>
    <%=link_to book.title, user_book_path(user, book)%>
    <br></br>
  <%end%>

app/views/users/_written-story-list.html.erb
<%user.books.each do |book|%>
  <%=link_to book.title, edit_user_book_path(user, book)%>
  <br></br>
<%end%>

app/views/users/blog.html.erb
<%if logged_in? && current_user==@user%>
  <%=link_to "Edit Blog", edit_blog_path%>
<%else%>
  <%=@user.username%>'s Blog
<%end%>

app/views/users/edit.html.erb
<%if logged_in? && current_user==@user%>
  <%=form_for @user do |f|%>
    <%= render :partial => "form", :locals=>{:f=>f} %>
    <%=f.label :password_confirmation%>
    <%=f.text_field :password_confirmation%>
  <br></br>
  <%=f.submit %>
  <%end%>
<%else%>
  <h2><%=@user.username%></h2>
  Sorry, you are not authorized to view this page.
<%end%>

app/views/users/editblog.html.erb
You're editing!

app/views/users/index.html.erb
<%@users.each do |user|%>
  <%=link_to user.username, user_path(user)%>
  <br></br>
<%end%>

app/views/users/new.html.erb
<%if !logged_in?%>
  <div id=signupForm>
  <%=form_for @user do |f|%>
    <%= render :partial => "form", :locals=>{:f=>f} %>
    <%=f.label :password_confirmation%>
    <%=f.text_field :password_confirmation, placeholder: "Confirm Password"%>
  <br></br>
  <%=f.submit %>
  <%end%>
  </div>
<%end%>

app/views/users/show.html.erb
<%if logged_in? && current_user==@user%>
    <%=link_to "Create a New Story", new_user_book_path(@user)%>
    <br></br>

Your Stories:
  <%=render partial: 'written-story-list', locals: {user: @user}%>
<br></br>
  <%=render partial: 'story_list', locals: {user: @user}%>

<%else%>
<h2><%=@user.username%>'s Featured Stories</h2>
<%book = @user.books.first%>
  <div>
    <h3 class="book-name"><%=book.title%></h3>
    <p class="book-summary"><%=book.summary%></p>
    <p class="book-genre"><p><%="Genre: " if book.genres.uniq.count != 0%><%book.genres.each do |g|%>
        <%=g.name%></p>
      <%end%></p>
  </div>
  <a href="#" class="js-next" data-id="<%=@user.books.first.id%>">Next</a>
  <!-- This is NOT doing anything
<a href="#" class="js-all">All Stories</a>-->
<%end%>
<br></br>

<%if @user.uid == nil && @user ==current_user%>
  <%=link_to "Edit User Profile", edit_user_path(@user)%>
<%end%>

<script type="text/javascript" charset="utf-8">

function getNextId() {
  let Id = parseInt($(".js-next").attr("data-id"))
  let newIndex = <%=@book_ids%>.indexOf(Id) + 1;
  if (<%=@book_ids%>.length === 1) {
    return Id
  } else return <%=@book_ids%>[newIndex]
}

$(function() {
  $('.js-next').on('click', function(e) {
    e.preventDefault()
    let nextId = getNextId();
    $.get("/books/"+nextId, function(data) {
      let book = data['data']['attributes']
      $(".book-name").text(book["title"])
      $(".book-genre").text(book["genres"].join(", "))
      $(".book-summary").text(book["summary"])
      $(".js-next").attr("data-id", nextId);
    }, "json")
  });
});
</script>

app/views/users/update.html.erb
<%=form_for @user do |f|%>
  <%= render :partial => "form", :locals=>{:f=>f} %>
  <%=f.label :password_confirmation%>
  <%=f.text_field :password_confirmation%>
<br></br>
<%=f.submit %>
<%end%>