config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :chapters
  resources :users, only: [:index, :create, :show, :edit, :destroy, :update] do
    resources :books, only: [:new, :show, :index, :edit]
  end
  resources :genres, only: [:index, :create, :show] do
    resources :books, only: [:index]
  end
  resources :books, only: [:index, :show, :create, :update, :destroy] do
    resources :comments, only: [:create]
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_FB'
  root 'application#index'
  post '/follow/:id' => 'books#follow', as: :follow
  get 'comments/:id/comment_data', to: 'comments#comment_data'
  delete '/comments' => 'comments#destroy', as: :destroy
  post '/unfollow/:id' => 'books#unfollow', as: :unfollow
  get '/hikari_faves' => 'books#hikari_faves'
  get '/users/:id/blog' => 'users#blog', as: :blog
  get '/users/:id/blog/edit' => 'users#editblog', as: :edit_blog

end

app/models/book.rb
class Book < ApplicationRecord
  has_many :comments
  has_many :book_genres
  has_many :genres, through: :book_genres
  has_many :user_books
  has_many :users, through: :user_books
  accepts_nested_attributes_for :users
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'FollowingFollower'
  has_many :followers, through:  :follower_relationships, source: :follower
  has_many :chapters

  validates :title, presence: true
  # validates :user_ids, presence: true

  def self.favs
     includes(:genres).where(genres: {name: "Yaoi"})
  end

  def self.delete_empties
    Book.all.where(title: nil).delete_all
  end

  def commenter_ids
    binding.pry
    self.comments.map {|c| c.user_id}
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :require_login
skip_before_action :require_login, only: [:index, :show]
before_action :set_book
skip_before_action :set_book, only: [:new, :create, :index, :edit, :hikari_faves]

  def index
    @user = User.find_by(id: params[:user_id])
    if params[:user_id]
      @books = User.find_by(id: params[:user_id]).books
    elsif params[:genre_id]
      @books = Genre.find_by(id: params[:genre_id]).books
      render json: @books
    else
      @books = Book.all
      respond_to do |format|
        format.html { render :index }
        format.json { render json: @books}
      end
    end

  end

  def new
    @book = Book.new(user_ids: params[:user_id])
  end

  def create
    @book = Book.create(book_params)
    if @book.invalid?
      render :new
    else
     @book.users << current_user if @book.save
     redirect_to book_path(@book)
    end
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @book}
    end
  end

  def edit
    if params[:user_id]
    @user = User.find_by(id: params[:user_id])
      if @user.nil?
        redirect_to users_path, alert: "Author not found."
      elsif  !@book = @user.books.find_by(id: params[:id])
        redirect_to user_books_path(@user), alert: "Book not found."
      else
        redirect_to user_books_path(@user) if logged_in? && !@book.users.find_by(id: current_user.id)
      end
    else
    @post = Post.find(params[:id])
    end
  end

  def update
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book.destroy

    redirect_to books_path
  end

  def follow
    @book.followers << current_user if !current_user.following.find_by(id: @book.id)
    redirect_to book_path(@book)
  end

  def unfollow
    current_user.following.delete(Book.find(@book.id)) if current_user.following.find_by(id: @book.id)
    redirect_to book_path(@book)
  end

  def hikari_faves
    @books = Book.favs
  end

  private

  def require_login
    redirect_to login_path if !logged_in?
  end

  def set_book
    @book = Book.find_by(id: params[:id])
  end

  def book_params
    params.require(:book).permit(:id, :title, :summary, genre_ids: [], user_ids: [], chapters: [])
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_add_chapter.html.erb
<%= form_tag ({controller: "chapters", action: "create", method: "post"}) do %>
  <%= text_field_tag "content" %>
  <%= hidden_field_tag "book_id", "#{@book.id}"%>
  <input type=submit value='Create Chapter'>
<% end %>

app/views/books/_book_list.html.erb
<%books.each do |book|%>
  <h3><%=link_to book.title, book_path(book)%></h3>
  <h3><%=book.users.uniq.count ==1 ? "Author:" : "Authors:"%>
  <%book.users.uniq.each do |user| %>
    <%=link_to user.username, user_path(user) if book.users%></h3>
  <%end%>
  <br>
  <p>
  <%= "Summary: " + book.summary if book.summary%></p>
  <br>
  <%="Genre: " if book.genres.uniq.count != 0%><%book.genres.each do |g|%>
      <%=link_to g.name, genre_path(g)%>
    <%end%>
<%end%>

app/views/books/_follow_books.html.erb
<%if logged_in? && current_user.following.find_by(id: book.id)%>
  <%=link_to "Unfollow", unfollow_path, method: :post%>
<%elsif logged_in?%>
  <%=link_to "Follow", follow_path, method: :post%>
<%else%>
<%end%>

app/views/books/_form.html.erb
<%if @book.errors.any?%>
<div id="error_explanation">
<h2><%=pluralize(@book.errors.count, "error")%> popped up:</h2>
  <%@book.errors.full_messages.each do |e|%>
  <li><%=e%></li>
</div>
  <%end%>
<%end%>


  <%=f.label :title%>
  <%=f.text_field :title%>
  <br></br>
  <%=f.label :summary%>
  <%=f.text_area :summary%>
  <br></br>

  Genre: <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name %>

app/views/books/edit.html.erb
<%=form_for @book do |f|%>
  <%= render partial: "form", :locals=>{:f=>f} %>
  <%=f.submit%>
<%end%>

Create New Chapter
<%=form_for @book do |f|%>
  <%= render partial: "add_chapter", :locals=>{:f=>f} %>
  <%=f.submit%>
<%end%>
<%= form_tag ({controller: 'books', action: 'destroy', method: 'delete'}) do %>
    <input id="hidden" type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type=submit value='Delete Story'>
<%end%>

app/views/books/hikari_faves.html.erb
<br>
<h1>Hikari Favorites</h1>
<%= render partial: "book_list", :locals=>{:books=>@books} %>

app/views/books/index.html.erb
<h3><%=@user.username + "'s Works" if @user%></h3>


<button id="sort-books">Sort Books</button>
<div id="book-list">
  <%= render partial: "book_list", :locals=>{:books=>@books} %>
</div>

app/views/books/new.html.erb
<%=form_for @book do |f|%>
<%= render partial: "form", :locals=>{:f=>f} %>
<%=f.submit%>

<%end%>

app/views/books/show.html.erb
<h2><%=@book.title%></h2>
<h3>
<!--BOOK INFO-->
  <%=@book.users.uniq.count ==1 ? "Author:" : "Authors:"%>
    <%@book.users.uniq.each do |user| %>
  <%=link_to user.username, user_path(user) if @book.users%></h3>
  <%end%>
<!--SUMARY AND GENRE-->
<p><%="Summary: " if @book.summary%><%=@book.summary%></p>
<p><%="Genre: " if @book.genres.uniq.count != 0%><%@book.genres.each do |g|%>
    <%=g.name%></p>
  <%end%>
<!--LIST COMMENTS-->

<%=render partial: 'comments/comments_list', locals: {comments: @book.comments}%>

<% if logged_in?%>
<!--LIST ADDING COMMENTS-->

<%=render partial: 'comments/add_comments', locals: {comments: @book.comments}%>

<!--LIST EDITING-->
  <%=link_to "Edit", edit_user_book_path(current_user, @book) if current_user.books.find_by(id: @book.id)%>
<!--FOLLOW BUTTON-->
  <%=render partial: 'follow_books', locals: {book: @book} if !current_user.books.find_by(id: @book.id)%>
<%end%>