config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :chapters
  resources :users, only: [:index, :create, :show, :edit, :destroy, :update] do
    resources :books, only: [:new, :show, :index, :edit]
  end
  resources :genres, only: [:index, :create, :show] do
    resources :books, only: [:index]
  end
  resources :books, only: [:index, :show, :create, :update, :destroy] do
    resources :comments, only: [:create]
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_FB'
  root 'application#index'
  post '/follow/:id' => 'books#follow', as: :follow
  get 'comments/:id/comment_data', to: 'comments#comment_data'
  delete '/comments' => 'comments#destroy', as: :destroy
  post '/unfollow/:id' => 'books#unfollow', as: :unfollow
  get '/hikari_faves' => 'books#hikari_faves'
  get '/users/:id/blog' => 'users#blog', as: :blog
  get '/users/:id/blog/edit' => 'users#editblog', as: :edit_blog

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
    @books = Book.all
  end

  def current_user
    User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  
end

app/views/application/index.html.erb
<body>
  <div class = "signupBlock">
    <div class="hikari-header">
      Welcome to Hikari!
    </div>
    <div class="signupOptions">
    <%if logged_in?%>
      <h3>Welcome, <%=link_to current_user.username, user_path(current_user)%></h3>
      <%=link_to 'logout', logout_path, method: :post%>
    <%else%>
      <%=link_to "Sign In", login_path%>
      <%=link_to "Sign Up", signup_path%>
      <%= link_to('Log in with Facebook!', '/auth/facebook') %>
    <%end%>
    </div>
  </div>
</body>