config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :chapters
  resources :users, only: [:index, :create, :show, :edit, :destroy, :update] do
    resources :books, only: [:new, :show, :index, :edit]
  end
  resources :genres, only: [:index, :create, :show] do
    resources :books, only: [:index]
  end
  resources :books, only: [:index, :show, :create, :update, :destroy] do
    resources :comments, only: [:create]
  end
  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_FB'
  root 'application#index'
  post '/follow/:id' => 'books#follow', as: :follow
  get 'comments/:id/comment_data', to: 'comments#comment_data'
  delete '/comments' => 'comments#destroy', as: :destroy
  post '/unfollow/:id' => 'books#unfollow', as: :unfollow
  get '/hikari_faves' => 'books#hikari_faves'
  get '/users/:id/blog' => 'users#blog', as: :blog
  get '/users/:id/blog/edit' => 'users#editblog', as: :edit_blog

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hikari Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="navbar">
      <%=link_to "All Books", books_path%>
      <%if logged_in?%>
        <h3>Welcome, <%=link_to current_user.username, user_path(current_user)%></h3>
        <%=link_to 'logout', logout_path, method: :post%>
      <%else%>
        <%=link_to "Log In", login_path%>
      <%end%>
    </div>
    <%= yield %>
  </body>
</html>